spring:
  datasource:
    username: root
    password: 123456
#    jdbc配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.111.83:3306/sell?useUnicode=true&characterEncoding=utf8
#    druid配置
    druid:
#      连接池配置 初始化连接池的数量大小 最小 最大
      initial-size: 10
      min-idle: 3
      max-active: 20
#      配置获取连接等待超时时间
      max-wait: 60000
#      配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
#      配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
#      是否缓存preparedStatement，也就是PSCache 官方建议关闭
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
    banner: false
    super-mapper-class: com.gentel.mybatisplus.framwork.mapper.BaseMapper
  type-enums-package: com.gentel.mybatisplus.enums
  type-aliases-package: com.gentel.mybatisplus.model.entity,com.gentel.mybatisplus.model.dto
logging:
  level:
    root: debug
